### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by billiemead** [mariojgt/onix-pro#5]
Laravel 6

Hi, after running composer require and publishing the files, I get a blank page when I visit URL/onix/grape

I tried to rerun npm install & npm run dev but still just a blank page. I don't believe the required dependencies are compiling.

**Comment by mariojgt** [comment]
Hi there i am not sure if is because you using laravel version 6 unfortunately my first release of the package was already for laravel 8 , because i am using all blade components inside component it may be something to do with the old version can't load blade components how laravel 8 does, but i just test i am fresh laravel 8 installation and was all good, if helps make sure to to run php artisan v:p --force and select the package provider but it may be because of the laravel 6 version.
